### PR TITLE
Upgrade GanetiMgr to Django v1.7.7 (Debian Jessie)

### PR DESCRIPTION
**Pull request by dblia**
Hello,

This patch set upgrades the GanetiMgr from Django 1.4 to Django 1.7.7, the
Debian Jessie supported version. It includes all the necessary functionality to
migrate to the Django v1.7 along with a couple of fixes mde during the migration
procedure. Also it updates the installation instructions to include the latest changes.
The branch has been tested on a clean Debian Jessie installation.

In brief, here are some of the most important changes introduced:

* Upgrading django template url tags to use the new syntax introduced in Django v1.5.
* Migrations are now built-in, so the South dependency has been removed.
* Upgrade the code to support the python-django-registration version 1.0.
* A fix in the gevent.pool.imap method invocation.
* The update of the 'ganeti/fields/jsonfield' module.

### CODE REVIEW

**Comment by sunweaver** [comment]
I have also a test installation running on Debian jessie based on this code base / patch set. Once merged, I have several more PR proposals for you.

**Comment by kroustou** [comment]
Hello @sunweaver , i already contacted @dblia in order to inform him that in the dev branch i have made a lot of changes. So i would suggest you to rebase to the dev branch. This pull request cannot be merged, but since we update the dev branch to 1.7 i can contact you. Thank you.

**Comment by kroustou** [comment]
Hello everyone,
I am pleased to tell you we finally managed to upgrade to django 1.7,
we have merged some of your commits and found some difficulties with 
other, such as:

1. Migrate code to django-registration v1.0
We had some problems with django-registration v1.0 (supported by Debian)
It does not appear to be working on django 1.7, and we switched to 
django-registration-redux (take a look at d107223492393a5867d73f3f52069dc20b531e04)

2. Explicitly set the TEST_RUNNER setting (https://github.com/skroutz/ganetimgr/commit/085c8593b5175c30c0430d397a14cf06f7232a20)
We used

        TEST_RUNNER = 'django.test.simple.DjangoTestSuiteRunner'

which seems to be working with the tests we've written

The code is under our dev branch

@sunweaver, @dblia  now that we have finished upgrading, you are more than welcome to
send us more PR!

**Comment by sunweaver** [comment]
Great! Will look into what I have here locally.

**Comment by sunweaver** [comment]
And... Django 1.9 has just entered Debian unstable... ;-)

**Pull request closed without merging**
